# Generated by Django 2.1.2 on 2018-12-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ipfs_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hash', models.CharField(max_length=250)),
                ('Host_Count', models.IntegerField()),
            ],
        ),
    ]
