# Generated by Django 2.1.2 on 2018-12-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipfs_details',
            name='id',
        ),
        migrations.AlterField(
            model_name='ipfs_details',
            name='Hash',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
